/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        ground: "var(--bg)",
        surface: "var(--surface)",
        hover: "var(--hover)",
        ink: "var(--text)",
        "ink-2": "var(--text-2)",
        "ink-3": "var(--text-3)",
        "ink-4": "var(--text-4)",
        faint: "var(--faint)",
        hairline: "var(--hairline)",
        accent: "var(--accent)",
        "accent-press": "var(--accent-link)",
        "accent-bg": "var(--accent-bg)",
        indigo: "var(--indigo)",
        heat: "var(--heat)",
        "heat-bg": "var(--heat-bg)",
        live: "var(--live)",
        "live-bg": "var(--live-bg)",
        track: "var(--track)",
        fill: "var(--fill)",
      },
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          "SF Pro Text",
          "SF Pro Display",
          "Helvetica Neue",
          "PingFang SC",
          "Hiragino Sans GB",
          "Microsoft YaHei",
          "sans-serif",
        ],
      },
      borderRadius: {
        pill: "999px",
        chip: "6px",
        thumb: "12px",
        sheet: "16px",
        card: "18px",
        panel: "22px",
        hero: "26px",
      },
      boxShadow: {
        card: "0 1px 2px rgba(0,0,0,0.04), 0 8px 24px rgba(0,0,0,0.05)",
        panel: "0 1px 3px rgba(0,0,0,0.05), 0 14px 40px rgba(0,0,0,0.05)",
        lift: "0 12px 32px rgba(0,0,0,0.1)",
        cta: "0 20px 54px rgba(0,113,227,0.24)",
        overlay: "0 2px 8px rgba(0,0,0,0.10), 0 30px 80px rgba(0,0,0,0.24)",
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.32, 0.72, 0, 1)",
        "out-quart": "cubic-bezier(0.25, 1, 0.5, 1)",
      },
    },
  },
  plugins: [],
};
